config/routes.rb
Rails.application.routes.draw do

  # /boards
  # /boards/:id
  resources :boards

  # full /pins resources
  resources :pins do
    resources :comments

    member do
      post '/repost' => 'pins#repost'
      get '/repost' => 'pins#show_repost'
    end

    member do
      post '/like' => 'pins#like'
    end
  end

  get '/:username' => 'users#show', as: 'user'

  devise_for :users
  root 'pins#index'
end

app/models/board.rb
class Board < ActiveRecord::Base

  belongs_to :user
  has_many :pins

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pin
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :pin
  validates_uniqueness_of :pin_id, scope: :user_id
  validates_presence_of :pin_id
  validates_presence_of :user_id
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  validates_presence_of :description, :image, :board_id
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def repost(edited_pin, user_object)
    repost_pin = self.dup
    repost_pin.board_id = edited_pin[:board_id]
    repost_pin.user_id = user_object.id
    repost_pin.image = self.image
    repost_pin.original_pin_id = self.id
    repost_pin.save
  end

  def is_repost?
    original_pin_id.present?
  end

  def original_pin
    Pin.find_by(id: original_pin_id) if is_repost?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :boards, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_pins, through: :likes, source: :pin

  validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :setup_devise_params, if: :devise_controller?

  protected

  def setup_devise_params
    devise_parameter_sanitizer.for(:sign_up) << [:username, :avatar]
    devise_parameter_sanitizer.for(:account_update) << [:username, :bio, :avatar]
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = current_user.boards.build
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.build(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to user_path(current_user.username), notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to user_path(current_user.username), notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user.username), notice: 'Board was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :description)
    end

    def correct_user
      @board = current_user.boards.find_by(id: params[:id])
      redirect_to boards_path, notice: "Not authorized to edit this board" if @board.nil?
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
   @pin = Pin.find(params[:pin_id])
   c_params = comment_params
   c_params["user_id"] = current_user.id
   p c_params
   @comment = @pin.comments.create(c_params)
   redirect_to pin_path(@pin)
 end

 private
   def comment_params
     params.require(:comment).permit(:body)
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :like, :repost, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pins_path, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_repost
    @pin = Pin.find(params[:id])
  end

  def repost
    @pin.repost(pin_params, current_user)
    redirect_to root_url
  end

  def like
    @like = @pin.likes.build(user_id: current_user.id)
    if @like.save
      flash[:notice] =  "You liked a Pin from #{@pin.user.username}!"
      redirect_to(pins_path)
    else
      flash[:notice] =  "You have already liked this Pin!"
      redirect_to(pins_path)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :board_id)
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by username: params[:username]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_controller_helper.rb
module BoardsControllerHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<%= form_for @board do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= render 'form' %>

app/views/boards/index.html.erb
<%= link_to "New board", new_board_path %>

<% @boards.each do |board| %>

  <div>
    <h2><%= board.name %></h2>
    <p><%= board.description %></p>
    <%= board.user_id %>
  </div>

<% end %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

app/views/boards/show.html.erb
<h3>
  <%= link_to image_tag(@board.user.avatar.url(:thumb)), user_path(@board.user.username) %>
  <%= link_to @board.user.username, user_path(@board.user.username) %>
</h3>
<p><%= @board.user.bio %></p>

<div class = "page-header">
  <h1><%= @board.name %></h1>
  <p><%= @board.description %></p>
  <% if @board.user == current_user %>
    <p>
      <%= link_to 'edit', edit_board_path(@board) %> |
      <%= link_to 'delete', @board, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</div>

<div class="grid row">
  <% @board.pins.each do |pin| %>
    <div class = "grid-item col-md-3 col-sm-4 col-xs-12">
      <div class = "pin grid-item-content">
        <div class = "pin-image">
          <%= link_to image_tag(pin.image.url(:medium)), pin %>
        </div>
        <div class = "pin-content">
          <div class = "pin-description">
            <%= pin.description %>
          </div>
          <div class = "user">
            <div class = "user-detail"><%= pin.user.username %></div>
            <% if pin.user == current_user %>
            <div class = "user-actions">
              <%= link_to 'Edit', edit_pin_path(pin) %>
              <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_header.html.erb
<div class="jumbotron">
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= image_tag('akane.png', size:'50', class: 'navbar-nav') %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Akane", root_path, class:"navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home ", root_path %></li>
        <li><%= link_to "Pins&Boards ", pins_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">New <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Pin', new_pin_path %></li>
            <li><%= link_to 'Board', new_board_path %></li>
          </ul>
        </li>
        <li><%= link_to current_user.username, user_path(current_user.username) %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="row">

    <div class="jumbotron background">
      <div class = "row">
      <div class = "col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3">
        <%= image_tag('akane', class: 'logo1') %>
      </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Akane</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'home/header' %>

  <div class = "container">

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin , html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :Image %>
    <%= f.file_field :image %>
  </div>
  <div class = "form-group">
    <%= f.label :board %>
    <%= f.select :board_id, options_from_collection_for_select(current_user.boards, "id", "name"), class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

app/views/pins/index.html.erb
<div class="grid row">
  <% @pins.each do |pin| %>
    <div class = "grid-item col-md-3 col-sm-4 col-xs-12">
      <div class = "pin grid-item-content">
        <div class = "pin-image">
          <%= link_to(image_tag(pin.image.url(:medium)), pin_path(pin)) %>
        </div>
        <div class = "pin-content">
          <div class = "pin-description">
            <%= pin.description %>
          </div>
          <div class = "user">
            <div class = "user-detail"><%= link_to pin.user.username, user_path(pin.user.username) %></div>
            <small>Posted in <%= link_to pin.board.name, pin.board %></small>
            <div class = "user-detail"><%= pluralize(pin.likes.count, "like") %></div>
            <div class = "user-actions">
              <% if pin.user != current_user && user_signed_in? %>
                <%= link_to 'Like', like_pin_path(pin), method: :post %>
                <%= link_to 'Repost', repost_pin_path(pin), class: 'pull-right' %>
              <% end %>
              <% if pin.is_repost? %>
                <p>I'm a repost!</p>
              <% end %>
              <% if pin.user == current_user %>
                <%= link_to 'Edit', edit_pin_path(pin) %>
                <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

app/views/pins/show.html.erb
<div class = "row">
  <div class = "col-md-8 col-md-offset-2">

    <p>Posted under: <%= link_to @pin.board.name, @pin.board %></p>

    <%= image_tag @pin.image.url, class: 'img-responsive', style: 'width: 100%' %>

    <%= @pin.description %>



    <h2>Comments</h2>

    <% @pin.comments.each do |comment| %>
      <p><%= comment.body %></p>
      <p>
        <strong><%= comment.user.username %></strong>
      </p>

      <hr>

    <% end %>

    <% if user_signed_in? %>
      <h2>Add a comment:</h2>
      <%= form_for([@pin, @pin.comments.build]) do |f| %>
        <p>
          <%= f.label :body %><br>
          <%= f.text_area :body %>
        </p>
        <p>
          <%= f.submit %>
        </p>
      <% end %>
    <% end %>

</div>
</div>

app/views/pins/show_repost.html.erb
<%= form_for @pin, url: repost_pin_path, method: :post do |f| %>
  <div class = "form-group">
    <%= f.label :board %>
    <%= f.select :board_id, options_from_collection_for_select(current_user.boards, "id", "name"), class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_profile.html.erb
<h3><%= image_tag(@user.avatar.url(:thumb)) %> <%= @user.username %></h3>
<p><%= @user.bio %></p>

<% if current_user == @user %>
  <%= link_to "Settings", edit_user_registration_path %>
<% end %>

app/views/users/show.html.erb
<h3>
  <%= link_to image_tag(@user.avatar.url(:thumb)), user_path(@user.username) %>
  <%= link_to @user.username, user_path(@user.username) %>
</h3>
<p><%= @user.bio %></p>
<% if current_user == @user %>
  <%= link_to "Settings", edit_user_registration_path %>
<% end %>

<div class = "page-header">
  <h1><%= @user.username.possessive %> boards</h1>
</div>


<div class="row grid" id = "boards" style = "margin-top: 30px">
<% @user.boards.each do |board| %>
  <div class = "col-md-3 grid-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= link_to board.name, board %>
        </h3>
      </div>
      <div class="panel-body">
        <%= link_to board do %>
          <% board.pins.take(1).each do |pin| %>
            <%= image_tag pin.image.url(:medium), style: 'width: 100%' %>
          <% end %>
        <% end %>
      </div>

        <div class="panel-footer">
          <%= board.description %>
        </div>

    </div>
  </div>
<% end %>
</div>